### PR TITLE
fix `cutoff` in LODE `TabulatedRadialIntegral`

### LINKED ISSUE #249: Spline tests fail in debug mode
running `RASCALINE_BUILD_TYPE=debug tox -e all-deps` gives the following failures:

```
FAILED python/rascaline/tests/utils/splines.py::test_fourier_space_spliner[0-1.0] - rascaline.status.RascalError: internal error (this is likely a bug, please report it): assertion failed: x >= self.parameters.start && x <= self.parameters.stop
FAILED python/rascaline/tests/utils/splines.py::test_fourier_space_spliner[0-0.0] - rascaline.status.RascalError: internal error (this is likely a bug, please report it): assertion failed: x >= self.parameters.start && x <= self.parameters.stop
FAILED python/rascaline/tests/utils/splines.py::test_fourier_space_spliner[1-1.0] - rascaline.status.RascalError: internal error (this is likely a bug, please report it): assertion failed: x >= self.parameters.start && x <= self.parameters.stop
FAILED python/rascaline/tests/utils/splines.py::test_fourier_space_spliner[1-0.0] - rascaline.status.RascalError: internal error (this is likely a bug, please report it): assertion failed: x >= self.parameters.start && x <= self.parameters.stop
```

This looks like we are trying to evaluate the spline outside of its definition domain. @PicoCentauri would you have time to look at it?

### PR DESCRIPTION
**Pull request by PicoCentauri**
Fixes #249 

The `cutoff` for the LODE `TabulatedRadialIntegral ` was set to real space environment  cutoff. This is wrong since for LODE we spline in k-space from 0 until the `k_cutoff`.

----
:books: Documentation preview :books:: https://rascaline--250.org.readthedocs.build/en/250/

### CODE REVIEW

File: rascaline/src/calculators/lode/radial_integral/spline.rs [hunk 1]
```diff
@@ -24,7 +24,7 @@ pub struct LodeRadialIntegralSplineParameters {
     pub max_radial: usize,
     /// Number of angular components
     pub max_angular: usize,
-    /// cutoff radius, this is also the maximal value that can be interpolated
+    /// k-space cutoff radius, this is also the maximal value that can be interpolated
     pub cutoff: f64,
```
Comment (PicoCentauri) [inline rascaline/src/calculators/lode/radial_integral/spline.rs:28]: Maybe we should call this also this `k_cutoff` to avoid confusion with the real space version?

Comment (Luthaf) [reply rascaline/src/calculators/lode/radial_integral/spline.rs:28]: yes, that sounds like a good idea!

File: rascaline/src/calculators/lode/radial_integral/spline.rs [hunk 2]
```diff
@@ -123,18 +123,17 @@ mod tests {
...
             max_angular: 10,
-            cutoff: 12.0,
+            k_cutoff: 10.0,
         };
 
         let gto = LodeRadialIntegralGto::new(LodeRadialIntegralGtoParameters {
             max_radial: parameters.max_radial,
             max_angular: parameters.max_angular,
-            cutoff: parameters.cutoff,
+            cutoff: 5.0,
```
Comment (PicoCentauri) [inline rascaline/src/calculators/lode/radial_integral/spline.rs:136]: I changed this value here to a different one as `k_cutoff`. Otherwise one might be confused why the real and the k-space cutoff has to be same.

Comment (Luthaf) [reply rascaline/src/calculators/lode/radial_integral/spline.rs:136]: 👍

**Review by Luthaf — APPROVED** [review]
